services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: edr
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - edr-network
  edr:
    build: ..
    environment:
      - EDR_DB_DSN=postgres://postgres:postgres@postgres:5432/edr?sslmode=disable
      - EDR_ADDR=0.0.0.0:8080
      - EDR_RULES_PATH=/rules
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ../rules:/rules:ro
    networks:
      - edr-network
    restart: unless-stopped

networks:
  edr-network:
    driver: bridge

volumes:
  pgdata:
