services:
  edr-server:
    build:
      context: ..
      dockerfile: build/Dockerfile.server
    environment:
      - EDR_RULES_DIR=/rules
      - EDR_SERVER_ADDR=:8080
      - EDR_SERVER_LOG_INGEST=1
    # Map container port 8080 to a RANDOM host port to avoid collisions
    ports:
      - "127.0.0.1::8080"

  ubuntu-agent:
    build:
      context: ..
      dockerfile: build/Dockerfile.ubuntu-vector
    depends_on:
      - edr-server
    environment:
      - EDR_SERVER_URL=http://edr-server:8080/ingest
    volumes:
      - ./vector/vector_config.toml:/etc/vector/vector.toml:ro
      - events_data:/data
      - vector_data:/var/lib/vector
    command: ["--config", "/etc/vector/vector.toml"]
    restart: on-failure

volumes:
  events_data: {}
  vector_data: {}
